const pocetnaPostignuca = [
    {
        sifra: "pocetno-1",
        naziv: "Prvi korak",
        opis: "Završi prvu lekciju",
        procjena: "30 min",
        zavrseno: false,
    },
    {
        sifra: "pocetno-2",
        naziv: "Hiragana početnik",
        opis: "Nauči 5 znakova",
        procjena: "45 min",
        zavrseno: true,
    },
    {
        sifra: "pocetno-3",
        naziv: "Katakana početnik",
        opis: "Nauči 5 znakova katakane",
        procjena: "45 min",
        zavrseno: false,
    },
    {
        sifra: "pocetno-4",
        naziv: "Hiragana starter",
        opis: "Završi prvi set znakova hiragane",
        procjena: "1 h",
        zavrseno: true,
    },
    /*
    {
        sifra: "pocetno-5",
        naziv: "Katakana starter",
        opis: "Završi prvi set znakova katakane",
        procjena: "1 h",
        zavrseno: false,
    },
    {
        sifra: "pocetno-6",
        naziv: "Prva riječ",
        opis: "Nauči 1 riječ",
        procjena: "5 min",
        zavrseno: true,
    },
    {
        sifra: "pocetno-7",
        naziv: "Prvih 10 riječi",
        opis: "Nauči 10 riječi",
        procjena: "45 min",
        zavrseno: false,
    },
    {
        sifra: "pocetno-8",
        naziv: "Brojevi",
        opis: "Nauči sve brojeve",
        procjena: "20 min",
        zavrseno: true,
    },
    {
        sifra: "pocetno-9",
        naziv: "Bez greške",
        opis: "Riješi lekciju bez ijedne greške",
        procjena: "45 min",
        zavrseno: false,
    },
    {
        sifra: "pocetno-10",
        naziv: "Brzo učiš!",
        opis: "Završi lekciju za manje od 10 minuta",
        procjena: "10 min",
        zavrseno: true,
    },
    {
        sifra: "pocetno-11",
        naziv: "Uči kontinuirano!",
        opis: "Uči 3 dana za redom",
        procjena: "3 dana",
        zavrseno: false,
    },
    {
        sifra: "pocetno-12",
        naziv: "Prvi kanji",
        opis: "Nauči svoj prvi kanji znak",
        procjena: "25 min",
        zavrseno: true,
    },
    {
        sifra: "pocetno-13",
        naziv: "Konnichiwa!",
        opis: "Nauči osnovne japanske pozdrave",
        procjena: "35 min",
        zavrseno: false,
    },
    {
        sifra: "pocetno-14",
        naziv: "Mini kviz",
        opis: "Riješi prvi kviz znanja",
        procjena: "15 min",
        zavrseno: true,
    },
    {
        sifra: "pocetno-15",
        naziv: "Točan odgovor",
        opis: "Odgovori točno na 10 pitanja zaredom",
        procjena: "15 min",
        zavrseno: false,
    },
    {
        sifra: "pocetno-16",
        naziv: "Noćna ptica",
        opis: "Završi lekciju nakon 22 h",
        procjena: "15 min",
        zavrseno: true,
    },
    {
        sifra: "pocetno-17",
        naziv: "Tko rano rani...",
        opis: "Započni lekciju prije 8 h",
        procjena: "20 min",
        zavrseno: false,
    },
    {
        sifra: "pocetno-18",
        naziv: "Trud se isplati!",
        opis: "Uči 5 dana za redom",
        procjena: "5 dana",
        zavrseno: true,
    },
    {
        sifra: "pocetno-19",
        naziv: "Prva rečenica",
        opis: "Sastavi svoju prvu rečenicu",
        procjena: "30 min",
        zavrseno: false,
    },
    {
        sifra: "pocetno-20",
        naziv: "Ponovi i savladaj",
        opis: "Ponovi jednu lekciju 3 puta",
        procjena: "40 min",
        zavrseno: true,
    },
    */
]

export const postignuca = [
    {
        sifra: 1,
        kategorija: "Početni napredak",
        postignuca: pocetnaPostignuca,
    },
    {
        sifra: 2,
        kategorija: "Učenje i znanje",
        postignuca: [],
    }
]