export const postignuca = [
    {
        sifra: '1',
        naziv: "Prvi korak",
        opis: "Završi prvu lekciju",
        kategorija: '1',
        procjena: 30,
        zavrseno: false,
    },
    {
        sifra: '2',
        naziv: "Hiragana početnik",
        opis: "Nauči 5 znakova",
        kategorija: '1',
        procjena: 45,
        zavrseno: true,
    },
    {
        sifra: '3',
        naziv: "Katakana početnik",
        opis: "Nauči 5 znakova katakane",
        kategorija: '1',
        procjena: 45,
        zavrseno: false,
    },
    {
        sifra: '4',
        naziv: "Prvih 10 riječi",
        opis: "Nauči 10 riječi",
        kategorija: '1',
        procjena: 45,
        zavrseno: false,
    },
    {
        sifra: '5',
        naziv: "Brojevi",
        opis: "Nauči sve brojeve",
        kategorija: '1',
        procjena: 20,
        zavrseno: true,
    },

    {
        sifra: '6',
        naziv: "Bez greške",
        opis: "Riješi lekciju bez ijedne greške",
        kategorija: '1',
        procjena: 45,
        zavrseno: false,
    },
    {
        sifra: '7',
        naziv: "Brzo učiš!",
        opis: "Završi lekciju za manje od 10 minuta",
        kategorija: '1',
        procjena: 10,
        zavrseno: true,
    },
    {
        sifra: '8',
        naziv: "Uči kontinuirano!",
        opis: "Uči 3 dana za redom",
        kategorija: '1',
        procjena: 4320,
        zavrseno: false,
    },
    {
        sifra: '9',
        naziv: "Prvi kanji",
        opis: "Nauči svoj prvi kanji znak",
        kategorija: '1',
        procjena: 25,
        zavrseno: true,
    },
    {
        sifra: '10',
        naziv: "Konnichiwa!",
        opis: "Nauči osnovne japanske pozdrave",
        kategorija: '1',
        procjena: 35,
        zavrseno: false,
    },
    {
        sifra: '11',
        naziv: "Hiragana starter",
        opis: "Završi prvi set znakova hiragane",
        kategorija: '2',
        procjena: 60,
        zavrseno: true,
    },

    {
        sifra: '12',
        naziv: "Katakana starter",
        opis: "Završi prvi set znakova katakane",
        kategorija: '2',
        procjena: 60,
        zavrseno: false,
    },
    {
        sifra: '13',
        naziv: "Prva riječ",
        opis: "Nauči 1 riječ",
        kategorija: '2',
        procjena: 5,
        zavrseno: true,
    },
    {
        sifra: '14',
        naziv: "Prva rečenica",
        opis: "Sastavi svoju prvu rečenicu",
        kategorija: '2',
        procjena: 30,
        zavrseno: false,
    },
    {
        sifra: '15',
        naziv: "Tko rano rani...",
        opis: "Započni lekciju prije 8 h",
        kategorija: '2',
        procjena: 20,
        zavrseno: false,
    },
    {
        sifra: '16',
        naziv: "Ponovi i savladaj",
        opis: "Ponovi jednu lekciju 3 puta",
        kategorija: '2',
        procjena: 40,
        zavrseno: true,
    },
    {
        sifra: '17',
        naziv: "Trud se isplati!",
        opis: "Uči 5 dana za redom",
        kategorija: '2',
        procjena: 7200,
        zavrseno: true,
    },
    {
        sifra: '18',
        naziv: "Noćna ptica",
        opis: "Završi lekciju nakon 22 h",
        kategorija: '2',
        procjena: 15,
        zavrseno: true,
    },
    {
        sifra: '19',
        naziv: "Točan odgovor",
        opis: "Odgovori točno na 10 pitanja zaredom",
        kategorija: '2',
        procjena: 15,
        zavrseno: false,
    },
    {
        sifra: '20',
        naziv: "Mini kviz",
        opis: "Riješi prvi kviz znanja",
        kategorija: '2',
        procjena: 15,
        zavrseno: true,
    },
]

export default {
    postignuca
}